[package]
name = "rsocks5"
version = "0.2.0"
edition = "2021"

[dependencies]
tokio = { version = "1.47.0", features = ["rt-multi-thread", "io-util", "net", "macros", "time"] }
log = "0.4"
env_logger = "0.11.8"
clap = { version = "4.4", features = ["derive"] }
